import { getDictionary } from '@lib/i18n';
import { Transaction } from './types';

type Dictionary = Awaited<ReturnType<typeof getDictionary>>;

export const getTransactions = (dict: Dictionary): Transaction[] => [
  {
    id: 'tx-1',
    name: 'Grocery Store Market',
    category: dict.categories_list.food,
    categoryIcon: 'icon-[fluent--food-20-regular] text-orange',
    categorySurfaceClass: 'bg-orange-surface',
    date: '2024-05-15T10:30:00',
    amount: -120.5,
    status: 'completed',
  },
  {
    id: 'tx-2',
    name: 'Tech Solutions Inc',
    category: dict.categories_list.income,
    categoryIcon: 'icon-[meteor-icons--dollar] text-green',
    categorySurfaceClass: 'bg-green-surface',
    date: '2024-05-18T14:15:00',
    amount: 3500.0,
    status: 'completed',
  },
  {
    id: 'tx-3',
    name: 'Netflix Subscription',
    category: dict.categories_list.entertainment,
    categoryIcon: 'icon-[hugeicons--tv-01] text-pink',
    categorySurfaceClass: 'bg-pink-surface',
    date: '2024-05-20T19:45:00',
    amount: -15.99,
    status: 'pending',
  },
  {
    id: 'tx-4',
    name: 'City Power & Light',
    category: dict.categories_list.utilities,
    categoryIcon: 'icon-[fluent--flash-20-regular] text-cyan',
    categorySurfaceClass: 'bg-cyan-surface',
    date: '2024-05-21T09:00:00',
    amount: -85.75,
    status: 'completed',
  },
  {
    id: 'tx-5',
    name: 'Uber Trip',
    category: dict.categories_list.transport,
    categoryIcon: 'icon-[raphael--bus] text-amber',
    categorySurfaceClass: 'bg-amber-surface',
    date: '2024-05-22T16:20:00',
    amount: -24.5,
    status: 'completed',
  },
  {
    id: 'tx-6',
    name: 'Online Course',
    category: dict.categories_list.education,
    categoryIcon: 'icon-[fluent--hat-graduation-20-regular] text-indigo',
    categorySurfaceClass: 'bg-indigo-surface',
    date: '2024-05-23T11:30:00',
    amount: -199.0,
    status: 'completed',
  },
  {
    id: 'tx-7',
    name: 'Gym Membership',
    category: dict.categories_list.health,
    categoryIcon: 'icon-[iconoir--heart] text-red',
    categorySurfaceClass: 'bg-red-surface',
    date: '2024-05-24T07:45:00',
    amount: -50.0,
    status: 'pending',
  },
  {
    id: 'tx-8',
    name: 'Freelance Project',
    category: dict.categories_list.income,
    categoryIcon: 'icon-[meteor-icons--dollar] text-green',
    categorySurfaceClass: 'bg-green-surface',
    date: '2024-05-25T13:10:00',
    amount: 1200.0,
    status: 'completed',
  },
  {
    id: 'tx-9',
    name: 'Cinema Ticket',
    category: dict.categories_list.entertainment,
    categoryIcon: 'icon-[hugeicons--tv-01] text-pink',
    categorySurfaceClass: 'bg-pink-surface',
    date: '2024-05-26T20:55:00',
    amount: -12.5,
    status: 'failed',
  },
  {
    id: 'tx-10',
    name: 'Gas Station',
    category: dict.categories_list.transport,
    categoryIcon: 'icon-[raphael--bus] text-amber',
    categorySurfaceClass: 'bg-amber-surface',
    date: '2026-01-08T18:30:00',
    amount: -45.0,
    status: 'completed',
  },
];
